// <auto-generated />
using System;
using Hesabdari_Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hesabdari_Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactsManager.Core.Domain.IdentityEntities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ContactsManager.Core.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtrasPrice")
                        .HasColumnType("int");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasBreakfast")
                        .HasColumnType("bit");

                    b.Property<int>("HeroSlidePrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("NumGuests")
                        .HasColumnType("int");

                    b.Property<int>("NumNights")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests", (string)null);
                });

            modelBuilder.Entity("Hesabdari_Core.Domain.Entities.HeroSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageDesktopJpgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("ImageDesktopWebpUrl")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("ImageMobileJpgUrl")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("ImageMobileWebpUrl")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeroSlides", (string)null);
                });
            
                modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    
                    b.Property<string>("PositionAndCompany")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("Content")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("ImageUrl")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Testimonials", (string)null);
                });
                
                modelBuilder.Entity("Hesabdari_Core.Domain.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    
                    b.Property<string>("FullName")
                     .IsRequired()
                     .HasColumnType("nvarchar(255)");
                    
                    b.Property<string>("Position")
                     .IsRequired()
                     .HasColumnType("nvarchar(255)");
                    
                    b.Property<string>("Bio")
                     .IsRequired()
                     .HasColumnType("nvarchar(255)");
                    
                    b.Property<string>("ImageUrl")
                     .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                     .IsRequired()
                     .HasColumnType("bit");

                    b.Property<int>("Order")
                     .IsRequired()
                     .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers", (string)null);
                });
                
                modelBuilder.Entity("Hesabdari_Core.Domain.Entities.ConsultationRequest", b =>
                {
                    b.Property<long>("Id")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    
                    b.Property<string>("FullName")
                     .IsRequired()
                     .HasColumnType("nvarchar(100)");
                    
                    b.Property<string>("CompanyName")
                     .HasColumnType("nvarchar(150)");
                    
                    b.Property<string>("Email")
                     .HasColumnType("nvarchar(255)");
                    
                    b.Property<string>("PhoneNumber")
                     .IsRequired()
                     .HasColumnType("nvarchar(30)");
                    
                    b.Property<string>("Description")
                     .IsRequired()
                     .HasColumnType("nvarchar(1000)");
                    
                    b.Property<string>("ServiceType")
                     .IsRequired()
                     .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                     .IsRequired()
                     .HasColumnType("bit");

                    b.Property<bool>("IsStarred")
                     .IsRequired()
                     .HasColumnType("bit");

                    b.Property<DateTime>("CreateAt")
                     .IsRequired()
                     .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConsultationRequests", (string)null);
                });

            modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("int");
                    
                    b.Property<string>("LogoImageUrl")
                     .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSlideAutoChangeEnabled")
                     .IsRequired()
                     .HasColumnType("bit");

                    b.Property<int>("SlideIntervalInSeconds")
                     .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Setting", (string)null);
                });
            
                modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");
                    
                    b.Property<string>("ShortDescription")
                     .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullDescription")
                     .IsRequired()
                     .HasColumnType("nvarchar(2000)");
                    
                    b.Property<long>("Price")
                     .HasColumnType("bigint");
                    
                    b.Property<string>("ImageUrl")
                     .HasColumnType("nvarchar(255)");
                    
                    b.Property<string>("IntroVideoUrl")
                     .IsRequired()
                     .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                     .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                     .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                     .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });
            
                modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                     .IsRequired()
                     .HasColumnType("nvarchar(255)");

                    b.Property<int>("Order")
                     .IsRequired()
                     .HasColumnType("int");

                    b.Property<int>("CourseId")
                     .IsRequired()
                     .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_Chapters_Courses_Id");

                    b.ToTable("Chapters", (string)null);
                });

                modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                     .IsRequired()
                     .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoUrl")
                     .IsRequired()
                     .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan>("Duration")
                     .IsRequired()
                     .HasColumnType("time");

                    b.Property<int>("Order")
                     .IsRequired()
                     .HasColumnType("int");

                    b.Property<bool>("IsFree")
                     .IsRequired()
                     .HasColumnType("bit");

                    b.Property<int>("ChapterId")
                     .IsRequired()
                     .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_Lessons_Chapter_Id");

                    b.ToTable("Lessons", (string)null);
                });
                
                modelBuilder.Entity("Hesabdari_Core.Domain.Entities.UserCourse", b =>
                {
                    b.Property<int>("Id")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserId")
                     .IsRequired()
                     .HasColumnType("uniqueidentifier");

                    b.Property<int>("CourseId")
                     .IsRequired()
                     .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_UserCourses_AspNetUsers_UserId");
                    b.HasIndex("FK_UserCourses_Courses_CourseId");

                    b.ToTable("UserCourses", (string)null);
                });


            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hesabdari_Core.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Hesabdari_Core.Domain.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ContactsManager.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ContactsManager.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ContactsManager.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ContactsManager.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManager.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ContactsManager.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
